export const SAVE_BUS_REQUEST = "SAVE_BUS_REQUEST";
export const FETCH_BUS_REQUEST = "FETCH_BUS_REQUEST";
export const UPDATE_BUS_REQUEST = "UPDATE_BUS_REQUEST";
export const DELETE_BUS_REQUEST = "DELETE_BUS_REQUEST";
export const BUS_SUCCESS = "BUS_SUCCESS";
export const BUS_FAILURE = "BUS_FAILURE";