export const SAVE_GARAGE_REQUEST = "SAVE_GARAGE_REQUEST";
export const FETCH_GARAGE_REQUEST = "FETCH_GARAGE_REQUEST";
export const UPDATE_GARAGE_REQUEST = "UPDATE_GARAGE_REQUEST";
export const DELETE_GARAGE_REQUEST = "DELETE_GARAGE_REQUEST";
export const GARAGE_SUCCESS = "GARAGE_SUCCESS";
export const GARAGE_FAILURE = "GARAGE_FAILURE";